// Pre-discovered Wikimedia Commons audio URLs bundled with the app.
// Generated by `npm run build:audio` (see scripts/build-audio.mjs).

import audioJson from "@/data/audio.json";

export interface CachedAudio {
  workTitle: string;
  workYear: number | null;
  // The performer / ensemble — present when the source is an Apple Music
  // preview, absent when the source is a Commons recording with no
  // attributable performer.
  artistName?: string;
  audioUrl: string;
  sourcePage: string | null;
  license: string;
  durationSeconds: number | null;
}

const CACHE: Record<string, CachedAudio> = audioJson as Record<
  string,
  CachedAudio
>;

export function getCachedAudio(composerId: string): CachedAudio | null {
  return CACHE[composerId] || null;
}

export function getCachedComposerIds(): string[] {
  return Object.keys(CACHE);
}
