import { PERIODS, type Period, getPeriodById } from "./periods";

export type Era = "medieval" | "renaissance" | "baroque" | "classical" | "romantic" | "20th-century";
export type PrimaryForm =
  | "orchestral"
  | "opera"
  | "chamber"
  | "keyboard"
  | "choral"
  | "song"
  | "ballet";

export interface SignatureWork {
  title: string;
  year: number | null; // null = uncertain / multi-year
  form: string; // free-text: "symphony", "string quartet", "opera", "piano sonata", etc.
}

export interface Composer {
  id: string;
  name: string;
  period: string; // period id
  era: Era;
  birthYear: number;
  deathYear: number | null;
  nationality: string;
  bio: string;
  primaryForm: PrimaryForm;
  // 4-7 signature works shown on reveal — the educational core.
  signatureWorks: SignatureWork[];
  // 4-6 stylistic "fingerprints" used as prompts in description mode.
  descriptionPrompts: string[];
  // In priority order. The build script tries each as a Wikimedia Commons
  // search query until it finds a usable audio file.
  audioSearchTerms: string[];
}

export const COMPOSERS: Composer[] = [
  // ============ Medieval ============
  {
    id: "hildegard",
    name: "Hildegard von Bingen",
    period: "medieval",
    era: "medieval",
    birthYear: 1098,
    deathYear: 1179,
    nationality: "German (Rhineland)",
    bio: "Benedictine abbess, mystic, theologian, scientist, and composer whose ecstatic monophonic chants — written for her own nuns — have re-entered the active repertoire only in our lifetime.",
    primaryForm: "choral",
    signatureWorks: [
      { title: "Ordo Virtutum", year: 1151, form: "morality play" },
      { title: "O virga ac diadema", year: null, form: "antiphon" },
      { title: "O ignis spiritus paracliti", year: null, form: "sequence" },
      { title: "Symphonia armoniae celestium revelationum", year: 1158, form: "song cycle" },
    ],
    descriptionPrompts: [
      "Medieval abbess whose visionary monophonic chants soar far above the standard chant range.",
      "Wrote what may be the earliest surviving morality play — characters debate over a single soul.",
      "Composed in ecstatic unison, with long melismas and an exceptionally wide vocal compass.",
      "One of the few women composers whose work survives from before 1500.",
    ],
    audioSearchTerms: [
      "Hildegard Bingen O frondens",
      "Hildegard Bingen",
      "Hildegard O virga",
    ],
  },
  {
    id: "perotin",
    name: "Pérotin",
    period: "medieval",
    era: "medieval",
    birthYear: 1160,
    deathYear: 1225,
    nationality: "French (Paris)",
    bio: "Composer at Notre-Dame de Paris around 1200, who took the two-voice organum of his predecessor Léonin and expanded it into vast three- and four-voice cathedral architectures.",
    primaryForm: "choral",
    signatureWorks: [
      { title: "Viderunt omnes", year: 1198, form: "organum quadruplum" },
      { title: "Sederunt principes", year: 1199, form: "organum quadruplum" },
      { title: "Alleluia Nativitas", year: null, form: "organum triplum" },
    ],
    descriptionPrompts: [
      "Notre-Dame Paris, c. 1200 — wrote the first four-voice polyphony of any ambition.",
      "Held long pedal-tones in the tenor while the upper voices spin out elaborate rhythmic patterns above.",
      "His 'Viderunt omnes' takes a single chant phrase and stretches it across many minutes of vast cathedral resonance.",
    ],
    audioSearchTerms: [
      "Perotin Viderunt omnes",
      "Perotin Sederunt principes",
      "Notre Dame organum Perotin",
    ],
  },
  {
    id: "machaut",
    name: "Guillaume de Machaut",
    period: "medieval",
    era: "medieval",
    birthYear: 1300,
    deathYear: 1377,
    nationality: "French",
    bio: "The towering figure of the 14th-century Ars Nova — poet, priest, courtier, and composer of secular songs and the first known polyphonic cycle of the Mass Ordinary by a single composer.",
    primaryForm: "choral",
    signatureWorks: [
      { title: "Messe de Nostre Dame", year: 1365, form: "mass" },
      { title: "Douce dame jolie", year: null, form: "virelai" },
      { title: "Ma fin est mon commencement", year: null, form: "rondeau" },
      { title: "Hoquetus David", year: null, form: "motet" },
    ],
    descriptionPrompts: [
      "14th-century French priest who wrote the first complete polyphonic Mass Ordinary by a single composer.",
      "His secular love songs — virelais, ballades, rondeaux — set his own poetry in elaborate rhythmic notation.",
      "Famous palindromic rondeau: 'My end is my beginning' — the music reads the same forwards and backwards.",
      "Defining figure of the Ars Nova: complex rhythm, isorhythmic motets, syncopation as a structural device.",
    ],
    audioSearchTerms: [
      "Machaut Messe de Nostre Dame Kyrie",
      "Machaut Douce dame jolie",
      "Machaut Ma fin est mon commencement",
    ],
  },

  // ============ Renaissance ============
  {
    id: "josquin",
    name: "Josquin des Prez",
    period: "renaissance",
    era: "renaissance",
    birthYear: 1450,
    deathYear: 1521,
    nationality: "Franco-Flemish",
    bio: "The central composer of the High Renaissance, called by Luther 'the master of the notes' — supreme practitioner of imitative polyphony in mass, motet, and chanson.",
    primaryForm: "choral",
    signatureWorks: [
      { title: "Missa Pange lingua", year: 1515, form: "mass" },
      { title: "Ave Maria... virgo serena", year: 1485, form: "motet" },
      { title: "Missa L'homme armé super voces musicales", year: 1490, form: "mass" },
      { title: "Mille regretz", year: null, form: "chanson" },
    ],
    descriptionPrompts: [
      "Franco-Flemish master, called 'master of the notes' by Luther — the highest expression of Renaissance polyphony.",
      "Voices enter one by one in imitation, weaving an unbroken vocal fabric.",
      "Wrote a famous Mass on the secular tune 'L'homme armé' that everyone in his era set.",
      "His 'Ave Maria... virgo serena' is the textbook example of late-15th-century imitative writing.",
    ],
    audioSearchTerms: [
      "Josquin Ave Maria virgo serena",
      "Josquin Missa Pange lingua",
      "Josquin Mille regretz",
    ],
  },
  {
    id: "palestrina",
    name: "Giovanni Pierluigi da Palestrina",
    period: "renaissance",
    era: "renaissance",
    birthYear: 1525,
    deathYear: 1594,
    nationality: "Italian (Rome)",
    bio: "Roman choirmaster whose impossibly smooth, controlled polyphonic style was adopted as the official model of post-Tridentine Catholic church music — and remained the textbook model of strict counterpoint into the 20th century.",
    primaryForm: "choral",
    signatureWorks: [
      { title: "Missa Papae Marcelli", year: 1562, form: "mass" },
      { title: "Sicut cervus", year: 1581, form: "motet" },
      { title: "Stabat Mater", year: 1590, form: "motet" },
      { title: "Missa Brevis", year: 1570, form: "mass" },
    ],
    descriptionPrompts: [
      "Roman master whose mass 'saved polyphony' (the legend says) by proving it could be intelligible.",
      "Wrote 105 masses — the absolute model of conservative, immaculate Counter-Reformation choral style.",
      "Every dissonance carefully prepared, every line conjunct — the textbook of 'strict' counterpoint to this day.",
      "Smooth-flowing imitative lines, fully sacred, almost no chromaticism.",
    ],
    audioSearchTerms: [
      "Palestrina Sicut cervus",
      "Palestrina Missa Papae Marcelli Kyrie",
      "Palestrina Stabat Mater",
    ],
  },
  {
    id: "byrd",
    name: "William Byrd",
    period: "renaissance",
    era: "renaissance",
    birthYear: 1543,
    deathYear: 1623,
    nationality: "English",
    bio: "Catholic composer at the Anglican court of Elizabeth I, who wrote Latin masses for private recusant worship and English anthems for the Chapel Royal — and the keyboard music that founded the English virginalist school.",
    primaryForm: "choral",
    signatureWorks: [
      { title: "Mass for Four Voices", year: 1593, form: "mass" },
      { title: "Mass for Five Voices", year: 1595, form: "mass" },
      { title: "Ave verum corpus", year: 1605, form: "motet" },
      { title: "The Earl of Salisbury Pavan", year: null, form: "keyboard" },
    ],
    descriptionPrompts: [
      "Catholic composer at the Protestant court of Elizabeth I — wrote masses for secret recusant worship.",
      "One of the founders of English keyboard music, in the My Ladye Nevells Booke and Fitzwilliam Virginal Book.",
      "Imitative writing in the Franco-Flemish tradition, but with a distinctly English sweetness.",
      "His three Latin masses (for 3, 4, and 5 voices) are the high point of Elizabethan Catholic music.",
    ],
    audioSearchTerms: [
      "Byrd Ave verum corpus",
      "Byrd Mass for Four Voices Kyrie",
      "Byrd Mass for Five Voices",
    ],
  },
  {
    id: "gesualdo",
    name: "Carlo Gesualdo",
    period: "renaissance",
    era: "renaissance",
    birthYear: 1566,
    deathYear: 1613,
    nationality: "Italian",
    bio: "Italian Prince of Venosa, murderer of his first wife and her lover, who in seclusion wrote some of the most chromatic, harmonically extreme vocal music in any era — sounding almost atonal in passages, three centuries before atonality arrived.",
    primaryForm: "choral",
    signatureWorks: [
      { title: "Madrigals, Book 5", year: 1611, form: "madrigals" },
      { title: "Madrigals, Book 6", year: 1611, form: "madrigals" },
      { title: "Tenebrae Responsories", year: 1611, form: "responsories" },
      { title: "Moro, lasso, al mio duolo", year: 1611, form: "madrigal" },
    ],
    descriptionPrompts: [
      "Italian prince and murderer whose madrigals are so chromatic they sound almost atonal.",
      "Composed under crushing personal guilt — his late madrigals warp Renaissance harmony beyond recognition.",
      "'I die, alas, in my suffering' — one of the most harmonically extreme works of the 1600s.",
      "Late Renaissance composer whose music had to wait until the 20th century to be properly heard.",
    ],
    audioSearchTerms: [
      "Gesualdo Moro lasso",
      "Gesualdo madrigals book 6",
      "Gesualdo Tenebrae Responsories",
    ],
  },

  // ============ Baroque ============
  {
    id: "monteverdi",
    name: "Claudio Monteverdi",
    period: "baroque",
    era: "baroque",
    birthYear: 1567,
    deathYear: 1643,
    nationality: "Italian (Cremona/Mantua/Venice)",
    bio: "The composer who bridged Renaissance and Baroque, whose 'L'Orfeo' of 1607 is the first opera that still holds the stage, and whose late Venetian operas wrote new emotional possibilities into the form.",
    primaryForm: "opera",
    signatureWorks: [
      { title: "L'Orfeo", year: 1607, form: "opera" },
      { title: "Vespro della Beata Vergine (Vespers of 1610)", year: 1610, form: "sacred" },
      { title: "L'incoronazione di Poppea", year: 1643, form: "opera" },
      { title: "Madrigals Book 8 (Madrigali guerrieri e amorosi)", year: 1638, form: "madrigals" },
    ],
    descriptionPrompts: [
      "Wrote the first opera that still holds the stage — 'L'Orfeo' of 1607.",
      "Bridged Renaissance polyphony and Baroque solo-with-continuo — pioneer of both styles.",
      "Famously divided music into the prima prattica (old polyphony) and seconda prattica (expressive new dissonance).",
      "Last opera 'L'incoronazione di Poppea' (1643) ends with Nero and his mistress crowned — moral evil triumphant, in music of stunning sensual beauty.",
    ],
    audioSearchTerms: [
      "Monteverdi Vespers 1610 Magnificat",
      "Monteverdi L'Orfeo Toccata",
      "Monteverdi Lamento della Ninfa",
    ],
  },
  {
    id: "purcell",
    name: "Henry Purcell",
    period: "baroque",
    era: "baroque",
    birthYear: 1659,
    deathYear: 1695,
    nationality: "English",
    bio: "The greatest English composer between Byrd and Elgar — dead at 36, having produced 'Dido and Aeneas,' a body of incidental theatre music, anthems for the Chapel Royal, and the most affecting English baroque songs.",
    primaryForm: "opera",
    signatureWorks: [
      { title: "Dido and Aeneas", year: 1689, form: "opera" },
      { title: "The Fairy-Queen", year: 1692, form: "semi-opera" },
      { title: "King Arthur", year: 1691, form: "semi-opera" },
      { title: "Music for the Funeral of Queen Mary", year: 1695, form: "funeral music" },
      { title: "Hail, bright Cecilia", year: 1692, form: "ode" },
    ],
    descriptionPrompts: [
      "Greatest English composer of the Baroque era — dead at 36 with 'Dido and Aeneas' to his name.",
      "Wrote a famous ground bass lament — 'When I am laid in earth, remember me, but ah, forget my fate.'",
      "His 'Funeral Music for Queen Mary' was played at his own funeral five months later.",
      "Anglican anthems for the Chapel Royal, brilliant theatre songs, the Welsh-tinged 'Music for a While.'",
    ],
    audioSearchTerms: [
      "Purcell Dido and Aeneas Dido's Lament",
      "Purcell When I am laid in earth",
      "Purcell Music for the Funeral of Queen Mary",
    ],
  },
  {
    id: "vivaldi",
    name: "Antonio Vivaldi",
    period: "baroque",
    era: "baroque",
    birthYear: 1678,
    deathYear: 1741,
    nationality: "Italian (Venice)",
    bio: "The 'Red Priest' of Venice — violin virtuoso, opera impresario, and resident composer at the Ospedale della Pietà girls' orphanage, for whose orchestra he wrote some 500 concertos. Died destitute in Vienna.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "The Four Seasons", year: 1725, form: "violin concerto cycle" },
      { title: "Gloria in D major, RV 589", year: 1715, form: "choral" },
      { title: "L'estro armonico (12 concertos)", year: 1711, form: "concertos" },
      { title: "La stravaganza (12 concertos)", year: 1716, form: "concertos" },
      { title: "Stabat Mater, RV 621", year: 1712, form: "choral" },
    ],
    descriptionPrompts: [
      "The 'Red Priest' of Venice who wrote 500 concertos for the girls' orchestra at the Ospedale della Pietà.",
      "Three-movement concerto form — fast / slow / fast — became the template for everyone after.",
      "Programmatic violin concertos depicting birdsong, storms, peasants drunk on the harvest, ice on a winter pond.",
      "Died destitute in Vienna; rediscovered in the 1920s and now one of the most-recorded composers in history.",
    ],
    audioSearchTerms: [
      "Vivaldi Spring Four Seasons",
      "Vivaldi Gloria RV 589",
      "Vivaldi Winter Four Seasons",
    ],
  },
  {
    id: "telemann",
    name: "Georg Philipp Telemann",
    period: "baroque",
    era: "baroque",
    birthYear: 1681,
    deathYear: 1767,
    nationality: "German (Hamburg)",
    bio: "The most prolific composer of the German Baroque, whose 3000+ works in every contemporary form were better-known than Bach's during his lifetime. Hamburg's musical director for 46 years.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Tafelmusik", year: 1733, form: "instrumental suites" },
      { title: "Paris Quartets", year: 1730, form: "chamber" },
      { title: "Brockes Passion", year: 1716, form: "oratorio" },
      { title: "Don Quichotte Suite", year: 1761, form: "orchestral" },
    ],
    descriptionPrompts: [
      "The most prolific German Baroque composer — outsold Bach during their lifetimes.",
      "Hamburg's musical director for nearly half a century, writing for every contemporary form.",
      "Tafelmusik ('table music') — three sumptuous suites for dinner-party entertainment of the German nobility.",
      "Light, elegant 'galant' style anticipating the Classical era better than any contemporary.",
    ],
    audioSearchTerms: [
      "Telemann Tafelmusik",
      "Telemann Paris Quartet",
      "Telemann Don Quichotte Suite",
    ],
  },
  {
    id: "rameau",
    name: "Jean-Philippe Rameau",
    period: "baroque",
    era: "baroque",
    birthYear: 1683,
    deathYear: 1764,
    nationality: "French",
    bio: "French Baroque master — provincial organist for fifty years, then suddenly the central figure of French opera in his fifties. His 'Traité de l'harmonie' (1722) is the founding text of functional tonality.",
    primaryForm: "opera",
    signatureWorks: [
      { title: "Hippolyte et Aricie", year: 1733, form: "tragédie en musique" },
      { title: "Les Indes galantes", year: 1735, form: "opéra-ballet" },
      { title: "Castor et Pollux", year: 1737, form: "opera" },
      { title: "Pièces de clavecin", year: 1724, form: "harpsichord" },
      { title: "Traité de l'harmonie", year: 1722, form: "treatise" },
    ],
    descriptionPrompts: [
      "His 'Treatise on Harmony' (1722) is the founding text of functional tonal theory.",
      "Provincial organist for fifty years — then became the central figure of French opera in his fifties.",
      "French Baroque dance suites and harpsichord pieces of crystalline elegance.",
      "Opera composer in the line of Lully — but with much richer harmony and orchestration.",
    ],
    audioSearchTerms: [
      "Rameau Les Indes galantes",
      "Rameau Castor et Pollux",
      "Rameau Pièces de clavecin",
    ],
  },
  {
    id: "bach",
    name: "Johann Sebastian Bach",
    period: "baroque",
    era: "baroque",
    birthYear: 1685,
    deathYear: 1750,
    nationality: "German (Eisenach/Leipzig)",
    bio: "Leipzig Thomaskantor for the last 27 years of his life, who in his 65 years wrote some 1100 surviving works that constitute the encyclopedic summit of Baroque polyphony.",
    primaryForm: "choral",
    signatureWorks: [
      { title: "St Matthew Passion", year: 1727, form: "passion" },
      { title: "Mass in B minor", year: 1749, form: "mass" },
      { title: "The Well-Tempered Clavier (Book 1)", year: 1722, form: "keyboard" },
      { title: "Brandenburg Concertos", year: 1721, form: "concerti grossi" },
      { title: "Goldberg Variations", year: 1741, form: "keyboard variations" },
      { title: "The Art of Fugue", year: 1750, form: "keyboard / unspecified" },
      { title: "Toccata and Fugue in D minor, BWV 565", year: null, form: "organ" },
    ],
    descriptionPrompts: [
      "Wrote a complete cycle of cantatas for every Sunday and feast of the church year — over 200 surviving.",
      "Two books of preludes and fugues, one in each major and minor key — the cornerstone of keyboard music.",
      "Encyclopedic master of fugue, counterpoint, and every Baroque form short of opera.",
      "His Mass in B minor and St Matthew Passion are the summits of Baroque sacred music.",
      "Last work, 'The Art of Fugue,' breaks off in the middle of a fugue spelling B-A-C-H in the soprano voice.",
    ],
    audioSearchTerms: [
      "Bach Toccata and Fugue in D minor BWV 565",
      "Bach Brandenburg Concerto No 3",
      "Bach Cello Suite No 1 Prelude",
      "Bach Air on the G string",
    ],
  },
  {
    id: "handel",
    name: "George Frideric Handel",
    period: "baroque",
    era: "baroque",
    birthYear: 1685,
    deathYear: 1759,
    nationality: "German-British",
    bio: "Born in Halle the same year as Bach, but moved to London at 27 and remade English oratorio. The 'Messiah' (1741) was a turning point in his career and a permanent fixture of Christmas ever since.",
    primaryForm: "opera",
    signatureWorks: [
      { title: "Messiah", year: 1741, form: "oratorio" },
      { title: "Water Music", year: 1717, form: "orchestral suite" },
      { title: "Music for the Royal Fireworks", year: 1749, form: "orchestral" },
      { title: "Giulio Cesare", year: 1724, form: "opera seria" },
      { title: "Zadok the Priest", year: 1727, form: "coronation anthem" },
      { title: "Rinaldo", year: 1711, form: "opera seria" },
    ],
    descriptionPrompts: [
      "Born in Halle the same year as Bach, but emigrated to London and remade English oratorio.",
      "'Messiah' (1741) and 'Hallelujah' chorus — at whose premiere George II reportedly stood, and we still do.",
      "Italian opera seria for the London stage in the 1720s — virtuoso castrati, da capo arias, dramatic recitative.",
      "Coronation anthem 'Zadok the Priest' has been played at every British coronation since 1727.",
    ],
    audioSearchTerms: [
      "Handel Messiah Hallelujah",
      "Handel Water Music Suite No 2",
      "Handel Zadok the Priest",
      "Handel Music for the Royal Fireworks",
    ],
  },
  {
    id: "scarlatti",
    name: "Domenico Scarlatti",
    period: "baroque",
    era: "baroque",
    birthYear: 1685,
    deathYear: 1757,
    nationality: "Italian (Naples) / Spanish",
    bio: "Born the same year as Bach and Handel, but escaped Italy to spend the last thirty years of his life as harpsichord teacher to the Spanish queen. Wrote 555 single-movement keyboard sonatas with no equal for inventiveness.",
    primaryForm: "keyboard",
    signatureWorks: [
      { title: "Keyboard Sonata in D minor, K. 9", year: null, form: "keyboard sonata" },
      { title: "Keyboard Sonata in E major, K. 380", year: null, form: "keyboard sonata" },
      { title: "Stabat Mater", year: 1715, form: "choral" },
      { title: "555 Keyboard Sonatas", year: null, form: "keyboard sonatas" },
    ],
    descriptionPrompts: [
      "Born 1685 (same year as Bach and Handel) — wrote 555 single-movement keyboard sonatas.",
      "Court keyboard teacher to the Spanish queen — absorbed Iberian guitar idiom into his harpsichord style.",
      "Each sonata a brilliant, brief virtuoso piece exploring a single idea — hand-crossings, repeated notes, sudden modulations.",
      "Italian Baroque master who anticipated the Classical-era piano sonata in everything but name.",
    ],
    audioSearchTerms: [
      "Scarlatti K 380",
      "Scarlatti K 9",
      "Scarlatti keyboard sonata K 466",
    ],
  },

  // ============ Classical ============
  {
    id: "haydn",
    name: "Joseph Haydn",
    period: "classical",
    era: "classical",
    birthYear: 1732,
    deathYear: 1809,
    nationality: "Austrian",
    bio: "Court Kapellmeister to Prince Esterházy for thirty years of relative isolation — long enough to codify, almost single-handedly, the Classical symphony (104 of them) and string quartet (68 of them).",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Symphony No. 94 'Surprise'", year: 1791, form: "symphony" },
      { title: "Symphony No. 104 'London'", year: 1795, form: "symphony" },
      { title: "The Creation", year: 1798, form: "oratorio" },
      { title: "String Quartet Op. 76, No. 3 'Emperor'", year: 1797, form: "string quartet" },
      { title: "Trumpet Concerto in E-flat", year: 1796, form: "concerto" },
      { title: "The Seasons", year: 1801, form: "oratorio" },
    ],
    descriptionPrompts: [
      "Codified the Classical symphony and string quartet — wrote 104 and 68 of them respectively.",
      "Court Kapellmeister to the Esterházy family for thirty years of relative isolation.",
      "Famous 'surprise' fortissimo chord in the slow movement of his Symphony No. 94 — said to startle dozing patrons.",
      "Wit, balance, sudden harmonic side-steps, formal clarity — the textbook Classical voice.",
      "His oratorio 'The Creation' opens with the most extraordinary depiction of chaos in 18th-century music.",
    ],
    audioSearchTerms: [
      "Haydn Symphony 94 Surprise",
      "Haydn Trumpet Concerto",
      "Haydn String Quartet Op 76 Emperor",
    ],
  },
  {
    id: "mozart",
    name: "Wolfgang Amadeus Mozart",
    period: "classical",
    era: "classical",
    birthYear: 1756,
    deathYear: 1791,
    nationality: "Austrian (Salzburg)",
    bio: "Child prodigy turned freelance master who, in 35 years, wrote 41 symphonies, 27 piano concertos, the great operas, the Requiem, and a single string quintet (K. 516) that may be the saddest music ever written.",
    primaryForm: "opera",
    signatureWorks: [
      { title: "The Marriage of Figaro", year: 1786, form: "opera buffa" },
      { title: "Don Giovanni", year: 1787, form: "opera" },
      { title: "The Magic Flute", year: 1791, form: "Singspiel" },
      { title: "Symphony No. 40 in G minor", year: 1788, form: "symphony" },
      { title: "Symphony No. 41 'Jupiter'", year: 1788, form: "symphony" },
      { title: "Requiem in D minor", year: 1791, form: "requiem mass" },
      { title: "Eine kleine Nachtmusik", year: 1787, form: "serenade" },
      { title: "Piano Concerto No. 21 in C major", year: 1785, form: "concerto" },
    ],
    descriptionPrompts: [
      "Child prodigy who toured Europe before he could shave — and wrote 41 symphonies before he died at 35.",
      "His three Da Ponte operas — Figaro, Don Giovanni, Così — set the bar for Western opera.",
      "Effortless melodic invention; transparent textures; a sense that the music writes itself.",
      "Final work — the unfinished Requiem — completed by his pupil Süssmayr from sketches and instructions.",
      "Don Giovanni dragged to hell by a statue of the man he murdered — 18th-century opera's most chilling scene.",
    ],
    audioSearchTerms: [
      "Mozart Eine kleine Nachtmusik",
      "Mozart Symphony 40 G minor",
      "Mozart Requiem Lacrimosa",
      "Mozart Marriage of Figaro Overture",
    ],
  },
  {
    id: "beethoven",
    name: "Ludwig van Beethoven",
    period: "classical",
    era: "classical",
    birthYear: 1770,
    deathYear: 1827,
    nationality: "German",
    bio: "Bonn-born, Vienna-based composer whose three creative periods carry music from inside the Classical style to its complete dismantling — and who went almost totally deaf in the process.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Symphony No. 3 'Eroica'", year: 1804, form: "symphony" },
      { title: "Symphony No. 5 in C minor", year: 1808, form: "symphony" },
      { title: "Symphony No. 9 'Choral'", year: 1824, form: "symphony" },
      { title: "Piano Sonata No. 14 'Moonlight'", year: 1801, form: "piano sonata" },
      { title: "Piano Sonata No. 23 'Appassionata'", year: 1805, form: "piano sonata" },
      { title: "String Quartet No. 14 in C-sharp minor, Op. 131", year: 1826, form: "string quartet" },
      { title: "Missa Solemnis", year: 1823, form: "mass" },
      { title: "Fidelio", year: 1814, form: "opera" },
    ],
    descriptionPrompts: [
      "Opens his Fifth Symphony with four hammer-strokes — the most famous opening in all of music.",
      "Went almost totally deaf and wrote the Ninth Symphony anyway — breaking the form open with the choral 'Ode to Joy.'",
      "Three creative periods — early (Haydn-Mozart inheritor), middle ('Heroic'), late (transcendent and strange).",
      "Late string quartets (Op. 127–135) sound like they were written 80 years ahead of their time.",
      "Wrote only one opera ('Fidelio'), one violin concerto, five piano concertos, nine symphonies — and remade all of them.",
    ],
    audioSearchTerms: [
      "Beethoven Symphony 5 first movement",
      "Beethoven Moonlight Sonata",
      "Beethoven Symphony 9 Ode to Joy",
      "Beethoven Für Elise",
    ],
  },

  // ============ Romantic ============
  {
    id: "schubert",
    name: "Franz Schubert",
    period: "romantic",
    era: "romantic",
    birthYear: 1797,
    deathYear: 1828,
    nationality: "Austrian (Vienna)",
    bio: "Dead at 31 from typhoid (or possibly syphilis), having written 600+ songs that single-handedly created the modern Lied, nine symphonies, the great string quintet, and Winterreise.",
    primaryForm: "song",
    signatureWorks: [
      { title: "Winterreise", year: 1827, form: "song cycle" },
      { title: "Die schöne Müllerin", year: 1823, form: "song cycle" },
      { title: "Symphony No. 8 'Unfinished'", year: 1822, form: "symphony" },
      { title: "Symphony No. 9 'Great'", year: 1826, form: "symphony" },
      { title: "String Quintet in C major, D. 956", year: 1828, form: "string quintet" },
      { title: "Ave Maria, D. 839", year: 1825, form: "song" },
      { title: "Erlkönig", year: 1815, form: "song" },
    ],
    descriptionPrompts: [
      "Wrote 600 songs in 31 years — invented the modern art song almost single-handedly.",
      "'Winterreise' (1827) — 24 songs of a rejected lover wandering frozen landscapes — written in the last year of his life.",
      "Symphony No. 8 'Unfinished' breaks off after two completed movements; we still play it that way.",
      "His string quintet's slow movement is one of music's most still and devastating passages.",
      "Friends gathered for 'Schubertiades' to hear new songs and piano music — the great chamber composer of intimacy.",
    ],
    audioSearchTerms: [
      "Schubert Ave Maria",
      "Schubert Erlkönig",
      "Schubert Symphony 8 Unfinished",
    ],
  },
  {
    id: "berlioz",
    name: "Hector Berlioz",
    period: "romantic",
    era: "romantic",
    birthYear: 1803,
    deathYear: 1869,
    nationality: "French",
    bio: "French Romantic visionary who reinvented the orchestra. His 'Symphonie fantastique' (1830) — autobiographical, drug-induced, programmatic — landed like a meteor; nothing in symphonic music after was quite the same.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Symphonie fantastique", year: 1830, form: "symphony" },
      { title: "Les Troyens", year: 1858, form: "opera" },
      { title: "Roméo et Juliette", year: 1839, form: "dramatic symphony" },
      { title: "Grande messe des morts (Requiem)", year: 1837, form: "requiem" },
      { title: "Harold en Italie", year: 1834, form: "viola concerto / symphony" },
    ],
    descriptionPrompts: [
      "'Symphonie fantastique' (1830) — an autobiographical drug trip leading to a witches' Sabbath in the finale.",
      "Reinvented the symphony orchestra — wrote the first authoritative treatise on orchestration.",
      "Wrote a five-hour epic opera, 'Les Troyens,' which the Paris Opera refused to stage in its entirety for a century.",
      "His Requiem demands four offstage brass bands and choirs of 200+.",
    ],
    audioSearchTerms: [
      "Berlioz Symphonie fantastique march to the scaffold",
      "Berlioz Symphonie fantastique witches sabbath",
      "Berlioz Roman Carnival Overture",
    ],
  },
  {
    id: "mendelssohn",
    name: "Felix Mendelssohn",
    period: "romantic",
    era: "romantic",
    birthYear: 1809,
    deathYear: 1847,
    nationality: "German",
    bio: "Prodigy from a wealthy Jewish-Christian Berlin family, who at 20 conducted the first performance of Bach's St Matthew Passion since the composer's death — and went on to write five concertos, five symphonies, and the supreme Romantic violin concerto.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Violin Concerto in E minor", year: 1844, form: "violin concerto" },
      { title: "Symphony No. 4 'Italian'", year: 1833, form: "symphony" },
      { title: "Symphony No. 3 'Scottish'", year: 1842, form: "symphony" },
      { title: "Elijah", year: 1846, form: "oratorio" },
      { title: "A Midsummer Night's Dream (overture)", year: 1826, form: "concert overture" },
      { title: "Songs Without Words", year: null, form: "piano" },
    ],
    descriptionPrompts: [
      "At twenty, conducted the first performance of Bach's St Matthew Passion since Bach died — single-handedly began the Bach revival.",
      "His Wedding March (from Midsummer Night's Dream) is played at half the weddings in the West.",
      "Combined Romantic feeling with absolute Classical formal clarity — the most classicising of the Romantics.",
      "Wrote his masterpiece violin concerto in collaboration with his concertmaster Ferdinand David.",
    ],
    audioSearchTerms: [
      "Mendelssohn Violin Concerto E minor",
      "Mendelssohn Midsummer Night Dream Overture",
      "Mendelssohn Symphony 4 Italian",
    ],
  },
  {
    id: "chopin",
    name: "Frédéric Chopin",
    period: "romantic",
    era: "romantic",
    birthYear: 1810,
    deathYear: 1849,
    nationality: "Polish-French",
    bio: "Polish-born, Paris-based piano poet who wrote almost exclusively for his own instrument and made it sing as no one had before — dying of tuberculosis at 39.",
    primaryForm: "keyboard",
    signatureWorks: [
      { title: "Ballade No. 1 in G minor", year: 1835, form: "piano ballade" },
      { title: "Nocturne in E-flat major, Op. 9 No. 2", year: 1832, form: "nocturne" },
      { title: "Préludes, Op. 28", year: 1839, form: "piano preludes" },
      { title: "Études, Op. 10", year: 1833, form: "études" },
      { title: "Piano Concerto No. 1 in E minor", year: 1830, form: "concerto" },
      { title: "Polonaise in A-flat major 'Heroic'", year: 1842, form: "polonaise" },
      { title: "Funeral March (Piano Sonata No. 2)", year: 1839, form: "piano sonata" },
    ],
    descriptionPrompts: [
      "Polish exile in Paris who wrote almost exclusively for the piano — and made it sing as no one had.",
      "Twenty-four Préludes, one in each major and minor key — concentrated lyric character pieces.",
      "Heart-on-sleeve nocturnes, polonaises that march for an exiled Poland, études as concert works.",
      "Tuberculosis killed him at 39; his heart is interred separately, in a Warsaw church.",
    ],
    audioSearchTerms: [
      "Chopin Nocturne Op 9 No 2",
      "Chopin Ballade No 1 G minor",
      "Chopin Funeral March Sonata",
    ],
  },
  {
    id: "schumann",
    name: "Robert Schumann",
    period: "romantic",
    era: "romantic",
    birthYear: 1810,
    deathYear: 1856,
    nationality: "German",
    bio: "Born the same year as Chopin and Liszt, Schumann was Romantic music's most literary figure — pianist, critic, novelistically imagined character-piece composer — and died in an asylum after attempting to drown himself in the Rhine.",
    primaryForm: "keyboard",
    signatureWorks: [
      { title: "Kinderszenen (Scenes from Childhood)", year: 1838, form: "piano cycle" },
      { title: "Dichterliebe", year: 1840, form: "song cycle" },
      { title: "Piano Concerto in A minor", year: 1845, form: "concerto" },
      { title: "Symphony No. 3 'Rhenish'", year: 1850, form: "symphony" },
      { title: "Carnaval, Op. 9", year: 1835, form: "piano cycle" },
      { title: "Frauenliebe und -leben", year: 1840, form: "song cycle" },
    ],
    descriptionPrompts: [
      "Most literary of the Romantics — composed character-piece cycles like 'Carnaval' that read as fiction.",
      "His 'Year of Song' (1840) produced 138 lieder — including 'Dichterliebe,' the supreme Romantic song cycle.",
      "Founded and edited the influential Neue Zeitschrift für Musik — first championed Brahms in print.",
      "Mental illness drove him to attempt suicide in the Rhine; he died in an asylum two years later.",
    ],
    audioSearchTerms: [
      "Schumann Träumerei Kinderszenen",
      "Schumann Piano Concerto A minor",
      "Schumann Carnaval",
    ],
  },
  {
    id: "liszt",
    name: "Franz Liszt",
    period: "romantic",
    era: "romantic",
    birthYear: 1811,
    deathYear: 1886,
    nationality: "Hungarian",
    bio: "Most spectacular pianist in history — invented the modern piano recital — who in his later years took minor orders in the Catholic Church and wrote increasingly austere, harmonically prophetic music.",
    primaryForm: "keyboard",
    signatureWorks: [
      { title: "Sonata in B minor", year: 1853, form: "piano sonata" },
      { title: "Liebestraum No. 3", year: 1850, form: "piano nocturne" },
      { title: "Hungarian Rhapsody No. 2", year: 1847, form: "rhapsody" },
      { title: "Années de pèlerinage", year: null, form: "piano cycle" },
      { title: "Piano Concerto No. 1 in E-flat", year: 1855, form: "concerto" },
      { title: "Faust Symphony", year: 1857, form: "symphony" },
    ],
    descriptionPrompts: [
      "Invented the modern piano recital — and was the first musician to be mobbed by fans (in the 1840s).",
      "His Sonata in B minor is a single half-hour movement that anticipates 20th-century structural thinking.",
      "Pioneer of the 'symphonic poem' — single-movement orchestral works following an extra-musical programme.",
      "Took minor orders in the Catholic Church in his fifties — late works grow harmonically prophetic and strange.",
    ],
    audioSearchTerms: [
      "Liszt Liebestraum No 3",
      "Liszt Hungarian Rhapsody 2",
      "Liszt La Campanella",
    ],
  },
  {
    id: "wagner",
    name: "Richard Wagner",
    period: "romantic",
    era: "romantic",
    birthYear: 1813,
    deathYear: 1883,
    nationality: "German",
    bio: "Reformed Romantic opera into the 'music drama' — long, continuous, mythic — culminating in the 17-hour Ring cycle. Built his own theatre at Bayreuth for it. Antisemite and ideological lightning rod ever since.",
    primaryForm: "opera",
    signatureWorks: [
      { title: "Der Ring des Nibelungen", year: 1876, form: "operatic cycle" },
      { title: "Tristan und Isolde", year: 1865, form: "opera" },
      { title: "Die Meistersinger von Nürnberg", year: 1868, form: "opera" },
      { title: "Parsifal", year: 1882, form: "opera / Bühnenweihfestspiel" },
      { title: "Tannhäuser", year: 1845, form: "opera" },
      { title: "Lohengrin", year: 1850, form: "opera" },
    ],
    descriptionPrompts: [
      "Wrote a 17-hour, four-opera cycle ('The Ring of the Nibelung') on Norse-German mythology.",
      "Built his own theatre at Bayreuth specifically to perform it; the festival continues to this day.",
      "His 'Tristan chord' — an unresolved chromatic dissonance — opened the door to 20th-century atonality.",
      "Pioneered the 'leitmotif': short musical themes attached to characters, ideas, or objects, woven through hours of music.",
      "Antisemitism and Hitler's late veneration have made him permanently controversial; the music remains overpowering.",
    ],
    audioSearchTerms: [
      "Wagner Ride of the Valkyries",
      "Wagner Tristan und Isolde Prelude",
      "Wagner Lohengrin Wedding March",
    ],
  },
  {
    id: "verdi",
    name: "Giuseppe Verdi",
    period: "romantic",
    era: "romantic",
    birthYear: 1813,
    deathYear: 1901,
    nationality: "Italian",
    bio: "Italy's national operatic poet — born the same year as Wagner, but pursued an entirely different ideal: bel canto melody, tight dramatic pacing, irresistible vocal writing for unforgettable characters.",
    primaryForm: "opera",
    signatureWorks: [
      { title: "La traviata", year: 1853, form: "opera" },
      { title: "Rigoletto", year: 1851, form: "opera" },
      { title: "Aida", year: 1871, form: "opera" },
      { title: "Otello", year: 1887, form: "opera" },
      { title: "Falstaff", year: 1893, form: "opera" },
      { title: "Il trovatore", year: 1853, form: "opera" },
      { title: "Requiem", year: 1874, form: "requiem mass" },
    ],
    descriptionPrompts: [
      "Italy's operatic poet — wrote 28 operas pursuing melodic ravishment and dramatic compression.",
      "His 'Va, pensiero' chorus from Nabucco became the unofficial anthem of Italian unification.",
      "Late operas (Otello, Falstaff) abandoned set-piece arias for continuous Shakespearean drama.",
      "His Requiem is theatrical Catholicism — Dies Irae as orchestral apocalypse.",
    ],
    audioSearchTerms: [
      "Verdi La donna è mobile Rigoletto",
      "Verdi Requiem Dies Irae",
      "Verdi Aida Triumphal March",
    ],
  },
  {
    id: "brahms",
    name: "Johannes Brahms",
    period: "romantic",
    era: "romantic",
    birthYear: 1833,
    deathYear: 1897,
    nationality: "German",
    bio: "Hamburg-born, Vienna-based conservative Romantic who argued with Beethoven's nine symphonies for forty years before producing four of his own. Burned more music than he published.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Symphony No. 1 in C minor", year: 1876, form: "symphony" },
      { title: "Symphony No. 4 in E minor", year: 1885, form: "symphony" },
      { title: "Ein deutsches Requiem", year: 1868, form: "requiem" },
      { title: "Violin Concerto in D major", year: 1878, form: "concerto" },
      { title: "Piano Concerto No. 2 in B-flat", year: 1881, form: "concerto" },
      { title: "Hungarian Dances", year: 1869, form: "orchestral / piano duet" },
      { title: "Clarinet Quintet in B minor", year: 1891, form: "chamber" },
    ],
    descriptionPrompts: [
      "Took twenty-one years to write his First Symphony — the weight of Beethoven's nine was that crushing.",
      "Conservative Romantic — defender of Classical form against the Wagner-Liszt 'New German School.'",
      "His 'German Requiem' uses Luther's Bible texts instead of the Latin Mass for the Dead.",
      "Burned everything he didn't think worthy — his teenage masterworks may have been incinerated by him.",
      "Bachelor for life; lived in Vienna; lifelong unconsummated love for Clara Schumann.",
    ],
    audioSearchTerms: [
      "Brahms Hungarian Dance No 5",
      "Brahms Symphony No 1 finale",
      "Brahms Lullaby",
    ],
  },
  {
    id: "tchaikovsky",
    name: "Pyotr Ilyich Tchaikovsky",
    period: "romantic",
    era: "romantic",
    birthYear: 1840,
    deathYear: 1893,
    nationality: "Russian",
    bio: "Russia's most famous melodist — six symphonies, three ballets, the violin concerto, the piano concerto, and an unhappy life of closeted homosexuality and apparent suicide by cholera-tainted water.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Symphony No. 6 'Pathétique'", year: 1893, form: "symphony" },
      { title: "Swan Lake", year: 1876, form: "ballet" },
      { title: "The Nutcracker", year: 1892, form: "ballet" },
      { title: "Piano Concerto No. 1 in B-flat minor", year: 1875, form: "concerto" },
      { title: "Violin Concerto in D major", year: 1878, form: "concerto" },
      { title: "1812 Overture", year: 1880, form: "concert overture" },
      { title: "Eugene Onegin", year: 1879, form: "opera" },
    ],
    descriptionPrompts: [
      "Russia's most famous melodist — three ballets, six symphonies, and the world's most-played piano concerto.",
      "His Sixth Symphony ends with a slow movement of devastating despair — premiered nine days before he died.",
      "'The Nutcracker' and 'Swan Lake' made him the founder of the modern ballet score.",
      "1812 Overture famously calls for cannon fire and church bells; commemorates Napoleon's retreat from Moscow.",
      "Closeted homosexuality and a disastrous brief marriage shadow his biography.",
    ],
    audioSearchTerms: [
      "Tchaikovsky 1812 Overture finale",
      "Tchaikovsky Nutcracker Dance of Sugar Plum Fairy",
      "Tchaikovsky Swan Lake theme",
      "Tchaikovsky Piano Concerto No 1",
    ],
  },
  {
    id: "mussorgsky",
    name: "Modest Mussorgsky",
    period: "romantic",
    era: "romantic",
    birthYear: 1839,
    deathYear: 1881,
    nationality: "Russian",
    bio: "Member of 'The Mighty Handful' — the nationalist Russian circle — and the most original of them, despite an alcoholism that destroyed him at 42. 'Boris Godunov' and 'Pictures at an Exhibition' are his.",
    primaryForm: "opera",
    signatureWorks: [
      { title: "Boris Godunov", year: 1869, form: "opera" },
      { title: "Pictures at an Exhibition", year: 1874, form: "piano suite" },
      { title: "Night on Bald Mountain", year: 1867, form: "tone poem" },
      { title: "Songs and Dances of Death", year: 1877, form: "song cycle" },
    ],
    descriptionPrompts: [
      "Russian nationalist whose 'Boris Godunov' is the great Russian opera — Tsar, monk, holy fool, Polish princess.",
      "His piano suite 'Pictures at an Exhibition' became famous in Ravel's orchestration.",
      "'Night on Bald Mountain' — a witches' sabbath made famous by Disney's 'Fantasia.'",
      "Rough-hewn, modal, deliberately ungrammatical by Western standards — his teachers tried to 'correct' it after his death.",
      "Alcoholism killed him at 42; left works in fragments his colleagues completed.",
    ],
    audioSearchTerms: [
      "Mussorgsky Night on Bald Mountain",
      "Mussorgsky Pictures at an Exhibition Promenade",
      "Mussorgsky Great Gate of Kiev",
    ],
  },
  {
    id: "dvorak",
    name: "Antonín Dvořák",
    period: "romantic",
    era: "romantic",
    birthYear: 1841,
    deathYear: 1904,
    nationality: "Czech",
    bio: "Czech butcher's son turned international celebrity — wrote nine symphonies and operas in Prague, then spent three years in New York directing the National Conservatory and writing the 'New World' Symphony.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Symphony No. 9 'From the New World'", year: 1893, form: "symphony" },
      { title: "Cello Concerto in B minor", year: 1895, form: "concerto" },
      { title: "String Quartet No. 12 'American'", year: 1893, form: "string quartet" },
      { title: "Slavonic Dances", year: 1878, form: "piano duet / orchestral" },
      { title: "Stabat Mater", year: 1877, form: "choral" },
      { title: "Rusalka", year: 1900, form: "opera" },
    ],
    descriptionPrompts: [
      "Czech composer who spent three years in New York directing the National Conservatory.",
      "His 'New World' Symphony (1893) draws on African-American spirituals and Native American melodies he'd heard.",
      "Bohemian folk-tinged melodies, naive lyric beauty, a generosity of melodic invention.",
      "His cello concerto is widely considered the greatest concerto written for the instrument.",
    ],
    audioSearchTerms: [
      "Dvorak New World Symphony Largo",
      "Dvorak Slavonic Dance No 8",
      "Dvorak Cello Concerto B minor",
    ],
  },

  // ============ Late Romantic ============
  {
    id: "mahler",
    name: "Gustav Mahler",
    period: "late-romantic",
    era: "20th-century",
    birthYear: 1860,
    deathYear: 1911,
    nationality: "Austrian (Bohemian-Jewish)",
    bio: "Conductor at the Vienna Hofoper for ten years, who in his summers wrote nine completed symphonies — vast, hour-long, autobiographical works that strain to contain everything from peasant dances to mystical visions.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Symphony No. 1 'Titan'", year: 1888, form: "symphony" },
      { title: "Symphony No. 2 'Resurrection'", year: 1894, form: "symphony" },
      { title: "Symphony No. 5", year: 1902, form: "symphony" },
      { title: "Symphony No. 9", year: 1909, form: "symphony" },
      { title: "Das Lied von der Erde", year: 1909, form: "symphony / song cycle" },
      { title: "Kindertotenlieder", year: 1904, form: "song cycle" },
    ],
    descriptionPrompts: [
      "Wrote nine vast symphonies that try to contain 'a whole world' — peasant dances, military marches, mystical visions.",
      "His Adagietto from the Fifth Symphony became famous in Visconti's 'Death in Venice.'",
      "Conducted at the Vienna Court Opera by day; composed feverishly in lakeside huts each summer.",
      "Death-haunted final works — Ninth Symphony, Das Lied von der Erde, unfinished Tenth — confront mortality directly.",
    ],
    audioSearchTerms: [
      "Mahler Symphony 5 Adagietto",
      "Mahler Symphony 1 Titan",
      "Mahler Resurrection Symphony",
    ],
  },
  {
    id: "strauss",
    name: "Richard Strauss",
    period: "late-romantic",
    era: "20th-century",
    birthYear: 1864,
    deathYear: 1949,
    nationality: "German",
    bio: "Wagner's most spectacular orchestral heir — made the orchestra a virtuoso narrative engine in his tone poems, then wrote 'Salome' and 'Elektra' before retreating into late-Romantic operas like 'Der Rosenkavalier.'",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Also sprach Zarathustra", year: 1896, form: "tone poem" },
      { title: "Don Juan", year: 1888, form: "tone poem" },
      { title: "Ein Heldenleben (A Hero's Life)", year: 1898, form: "tone poem" },
      { title: "Salome", year: 1905, form: "opera" },
      { title: "Der Rosenkavalier", year: 1911, form: "opera" },
      { title: "Four Last Songs", year: 1948, form: "orchestral songs" },
    ],
    descriptionPrompts: [
      "His 'Also sprach Zarathustra' opening became the soundtrack of Kubrick's '2001: A Space Odyssey.'",
      "Pushed the orchestra to virtuoso narrative limits in his tone poems of the 1890s.",
      "Wrote 'Salome' and 'Elektra' as one-act expressionist shocks, then retreated into the lush 'Rosenkavalier.'",
      "Outlived both world wars; his late 'Four Last Songs' (1948) are a serene farewell.",
    ],
    audioSearchTerms: [
      "Strauss Also sprach Zarathustra Introduction",
      "Strauss Don Juan opening",
      "Strauss Rosenkavalier suite",
    ],
  },
  {
    id: "sibelius",
    name: "Jean Sibelius",
    period: "late-romantic",
    era: "20th-century",
    birthYear: 1865,
    deathYear: 1957,
    nationality: "Finnish",
    bio: "Finland's national composer — seven symphonies, a violin concerto, 'Finlandia' — then thirty years of writing nothing in his retreat at Ainola. Possibly burned an Eighth Symphony in 1945.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Symphony No. 5", year: 1915, form: "symphony" },
      { title: "Symphony No. 2", year: 1902, form: "symphony" },
      { title: "Symphony No. 7", year: 1924, form: "symphony" },
      { title: "Violin Concerto in D minor", year: 1904, form: "concerto" },
      { title: "Finlandia", year: 1899, form: "tone poem" },
      { title: "The Swan of Tuonela", year: 1895, form: "tone poem" },
    ],
    descriptionPrompts: [
      "Finland's national composer — 'Finlandia' (1899) became an anthem of independence from Russia.",
      "Distilled the symphonic Romantic tradition into something austere, organic, and structurally radical.",
      "Stopped composing entirely in his sixties — thirty silent years at his retreat Ainola.",
      "Reputedly burned an Eighth Symphony in the stove around 1945; the world has been mourning it ever since.",
    ],
    audioSearchTerms: [
      "Sibelius Finlandia",
      "Sibelius Violin Concerto D minor",
      "Sibelius Symphony 2 finale",
    ],
  },
  {
    id: "puccini",
    name: "Giacomo Puccini",
    period: "late-romantic",
    era: "20th-century",
    birthYear: 1858,
    deathYear: 1924,
    nationality: "Italian",
    bio: "Verdi's most direct operatic heir — perfected the heart-on-sleeve Italian lyric style in 'La Bohème,' 'Tosca,' 'Madama Butterfly,' and the unfinished 'Turandot.'",
    primaryForm: "opera",
    signatureWorks: [
      { title: "La Bohème", year: 1896, form: "opera" },
      { title: "Tosca", year: 1900, form: "opera" },
      { title: "Madama Butterfly", year: 1904, form: "opera" },
      { title: "Turandot", year: 1926, form: "opera" },
      { title: "Gianni Schicchi", year: 1918, form: "opera" },
    ],
    descriptionPrompts: [
      "Italian opera's last great melodist — 'La Bohème,' 'Tosca,' 'Madama Butterfly,' 'Turandot.'",
      "Wrote some of the most popular arias ever — 'Nessun dorma,' 'O mio babbino caro,' 'E lucevan le stelle.'",
      "Died of throat cancer leaving 'Turandot' unfinished; the conductor at the premiere stopped where Puccini stopped.",
      "Heart-on-sleeve melody, harmonic richness, brutal melodramatic plotting — the late Romantic Italian school.",
    ],
    audioSearchTerms: [
      "Puccini O mio babbino caro",
      "Puccini Nessun dorma",
      "Puccini Madama Butterfly Un bel dì",
    ],
  },
  {
    id: "rachmaninoff",
    name: "Sergei Rachmaninoff",
    period: "late-romantic",
    era: "20th-century",
    birthYear: 1873,
    deathYear: 1943,
    nationality: "Russian",
    bio: "Last great Russian Romantic — pianist of enormous hands, conductor, and composer whose post-revolutionary American exile preserved Tchaikovsky-style lush melodism well into the era of Stravinsky and Schoenberg.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Piano Concerto No. 2 in C minor", year: 1901, form: "concerto" },
      { title: "Piano Concerto No. 3 in D minor", year: 1909, form: "concerto" },
      { title: "Rhapsody on a Theme of Paganini", year: 1934, form: "piano and orchestra" },
      { title: "Symphony No. 2 in E minor", year: 1907, form: "symphony" },
      { title: "Prelude in C-sharp minor", year: 1892, form: "piano prelude" },
      { title: "Vespers (All-Night Vigil)", year: 1915, form: "choral" },
    ],
    descriptionPrompts: [
      "Last great Russian Romantic — wrote lush melodic concertos well into the era of Stravinsky and Schoenberg.",
      "Had enormous hands that could span a twelfth on the keyboard — wrote piano music almost no one else can play.",
      "His Second Piano Concerto saved his composing career after a nervous breakdown over the Symphony No. 1 failure.",
      "Fled Russia after the 1917 Revolution; spent the rest of his life in American exile, mostly conducting.",
    ],
    audioSearchTerms: [
      "Rachmaninoff Piano Concerto 2 opening",
      "Rachmaninoff Rhapsody on a Theme of Paganini 18th variation",
      "Rachmaninoff Prelude C sharp minor",
    ],
  },

  // ============ Impressionism ============
  {
    id: "debussy",
    name: "Claude Debussy",
    period: "impressionism",
    era: "20th-century",
    birthYear: 1862,
    deathYear: 1918,
    nationality: "French",
    bio: "Father of musical Impressionism — drew on Javanese gamelan, whole-tone scales, modal harmony, and non-functional chord-streams to invent a new harmonic vocabulary for the 20th century.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Prélude à l'après-midi d'un faune", year: 1894, form: "tone poem" },
      { title: "La Mer", year: 1905, form: "orchestral suite" },
      { title: "Clair de lune (Suite bergamasque)", year: 1905, form: "piano" },
      { title: "Préludes (Books 1 and 2)", year: 1913, form: "piano" },
      { title: "Pelléas et Mélisande", year: 1902, form: "opera" },
      { title: "String Quartet in G minor", year: 1893, form: "chamber" },
    ],
    descriptionPrompts: [
      "Father of musical Impressionism — substituted colour and atmosphere for German psychological argument.",
      "Heard Javanese gamelan at the 1889 Paris Exposition; the modal and percussive influence is everywhere in his music.",
      "His 'Prélude à l'après-midi d'un faune' (1894) is often called the first piece of 20th-century music.",
      "Pioneered the whole-tone scale, parallel chord-streams, and a harmony detached from functional resolution.",
    ],
    audioSearchTerms: [
      "Debussy Clair de lune",
      "Debussy La Mer",
      "Debussy Prelude L'après-midi d'un faune",
    ],
  },
  {
    id: "ravel",
    name: "Maurice Ravel",
    period: "impressionism",
    era: "20th-century",
    birthYear: 1875,
    deathYear: 1937,
    nationality: "French (Basque)",
    bio: "Shared Debussy's harmonic vocabulary but was a more precise classicist by temperament — a meticulous craftsman of orchestral colour and miniaturist forms.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Boléro", year: 1928, form: "orchestral" },
      { title: "Daphnis et Chloé", year: 1912, form: "ballet" },
      { title: "Piano Concerto in G", year: 1931, form: "concerto" },
      { title: "Piano Concerto for the Left Hand", year: 1930, form: "concerto" },
      { title: "Gaspard de la nuit", year: 1908, form: "piano" },
      { title: "Pavane pour une infante défunte", year: 1899, form: "piano / orchestral" },
    ],
    descriptionPrompts: [
      "Shared Debussy's harmonic palette but was a Swiss-watchmaker craftsman by temperament.",
      "'Boléro' (1928) — a single rhythmic ostinato repeated for 15 minutes, building inexorably to its final blare.",
      "Wrote a Piano Concerto for the Left Hand for Paul Wittgenstein, who'd lost his right arm in WWI.",
      "Orchestrated Mussorgsky's 'Pictures at an Exhibition' — and made it the version everyone now plays.",
    ],
    audioSearchTerms: [
      "Ravel Bolero",
      "Ravel Pavane pour une infante défunte",
      "Ravel Piano Concerto G major adagio",
    ],
  },
  {
    id: "satie",
    name: "Erik Satie",
    period: "impressionism",
    era: "20th-century",
    birthYear: 1866,
    deathYear: 1925,
    nationality: "French",
    bio: "Eccentric Parisian — wore identical grey velvet suits, never bathed, lived in a one-room apartment no one entered while he lived — whose ironic, ascetic piano miniatures were the anti-Romantic conscience of his era.",
    primaryForm: "keyboard",
    signatureWorks: [
      { title: "Gymnopédies (Nos. 1-3)", year: 1888, form: "piano" },
      { title: "Gnossiennes", year: 1890, form: "piano" },
      { title: "Vexations", year: 1893, form: "piano" },
      { title: "Parade (ballet)", year: 1917, form: "ballet" },
      { title: "Socrate", year: 1918, form: "symphonic drama" },
    ],
    descriptionPrompts: [
      "Eccentric Parisian who wore identical grey velvet suits and never let anyone into his one-room apartment.",
      "His three Gymnopédies (1888) — sparse, modal, melancholy — invented the genre we now call 'ambient.'",
      "Wrote 'Vexations,' a short piano piece marked to be repeated 840 times — a 19-hour performance.",
      "Wit, irony, anti-Romantic asceticism — the conscience against which Debussy and Ravel could be measured.",
    ],
    audioSearchTerms: [
      "Satie Gymnopédie No 1",
      "Satie Gnossienne No 1",
      "Satie Trois Gymnopédies",
    ],
  },

  // ============ Modernism ============
  {
    id: "stravinsky",
    name: "Igor Stravinsky",
    period: "modernism",
    era: "20th-century",
    birthYear: 1882,
    deathYear: 1971,
    nationality: "Russian-French-American",
    bio: "Three styles in three lives — primitivist Russian ballet master (Firebird, Petrushka, Rite of Spring), neoclassical reorganiser (Symphony of Psalms, Apollo), late serialist (Threni, Movements). Always one step ahead.",
    primaryForm: "ballet",
    signatureWorks: [
      { title: "The Rite of Spring", year: 1913, form: "ballet" },
      { title: "The Firebird", year: 1910, form: "ballet" },
      { title: "Petrushka", year: 1911, form: "ballet" },
      { title: "Symphony of Psalms", year: 1930, form: "choral symphony" },
      { title: "The Soldier's Tale", year: 1918, form: "theatre piece" },
      { title: "Symphony in Three Movements", year: 1945, form: "symphony" },
    ],
    descriptionPrompts: [
      "The most famous riot in concert history — at the 1913 Paris premiere of his 'Rite of Spring.'",
      "Three completely different styles across his career — primitivist, neoclassical, serialist.",
      "Asymmetric rhythms, polytonal chords, percussive orchestration — remade what music could sound like.",
      "Worked with Diaghilev's Ballets Russes; later lived in Hollywood and New York.",
    ],
    audioSearchTerms: [
      "Stravinsky Firebird Suite finale",
      "Stravinsky Rite of Spring Augurs of Spring",
      "Stravinsky Petrushka Russian Dance",
    ],
  },
  {
    id: "schoenberg",
    name: "Arnold Schoenberg",
    period: "modernism",
    era: "20th-century",
    birthYear: 1874,
    deathYear: 1951,
    nationality: "Austrian-American (Jewish)",
    bio: "Self-taught Viennese painter and composer whose 1908 'free atonality' broke from tonal harmony, and whose 1920s twelve-tone method gave that break a systematic basis. Fled the Nazis in 1933.",
    primaryForm: "chamber",
    signatureWorks: [
      { title: "Verklärte Nacht", year: 1899, form: "string sextet / orchestral" },
      { title: "Pierrot lunaire", year: 1912, form: "chamber song cycle" },
      { title: "Five Pieces for Orchestra, Op. 16", year: 1909, form: "orchestral" },
      { title: "Suite for Piano, Op. 25", year: 1923, form: "piano suite" },
      { title: "A Survivor from Warsaw", year: 1947, form: "narrator / chorus / orchestra" },
      { title: "Moses und Aron", year: 1957, form: "opera" },
    ],
    descriptionPrompts: [
      "Broke from tonality in 1908; invented the twelve-tone method around 1923 to systematize that break.",
      "'Pierrot lunaire' (1912) introduced Sprechstimme — a half-spoken, half-sung delivery — to chamber music.",
      "Each twelve-tone work derives its entire pitch material from a single ordering of the chromatic scale.",
      "Fled the Nazis to Los Angeles in 1933 — taught at UCLA and reconverted to Judaism.",
    ],
    audioSearchTerms: [
      "Schoenberg Verklärte Nacht",
      "Schoenberg Pierrot lunaire",
      "Schoenberg Five Pieces for Orchestra",
    ],
  },
  {
    id: "bartok",
    name: "Béla Bartók",
    period: "modernism",
    era: "20th-century",
    birthYear: 1881,
    deathYear: 1945,
    nationality: "Hungarian",
    bio: "Pioneer ethnomusicologist who recorded thousands of peasant songs across Hungary, Romania, Slovakia, and beyond — then fused that folk modality with rigorous Modernist construction.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Concerto for Orchestra", year: 1943, form: "orchestral" },
      { title: "Music for Strings, Percussion and Celesta", year: 1936, form: "chamber orchestra" },
      { title: "String Quartet No. 4", year: 1928, form: "string quartet" },
      { title: "String Quartet No. 5", year: 1934, form: "string quartet" },
      { title: "Mikrokosmos", year: 1939, form: "piano teaching pieces" },
      { title: "Bluebeard's Castle", year: 1911, form: "opera" },
    ],
    descriptionPrompts: [
      "Recorded thousands of folk songs across Eastern Europe — pioneer ethnomusicologist.",
      "Fused that peasant modality with the rigorous Modernist construction of Schoenberg's Vienna.",
      "Wrote six string quartets that are the most important quartet cycle since Beethoven.",
      "Fled Hungary in 1940 for the US; died of leukaemia in 1945 in a New York hospital, almost forgotten.",
    ],
    audioSearchTerms: [
      "Bartok Romanian Folk Dances",
      "Bartok Concerto for Orchestra",
      "Bartok Music for Strings Percussion Celesta",
    ],
  },
  {
    id: "prokofiev",
    name: "Sergei Prokofiev",
    period: "modernism",
    era: "20th-century",
    birthYear: 1891,
    deathYear: 1953,
    nationality: "Russian (Soviet)",
    bio: "Russian prodigy who emigrated after the Revolution, lived in Paris and California, then unwisely returned to Stalin's USSR in 1936. Died on the same day as Stalin in 1953 — his death was barely noticed.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Romeo and Juliet", year: 1935, form: "ballet" },
      { title: "Peter and the Wolf", year: 1936, form: "narrated children's piece" },
      { title: "Piano Concerto No. 3 in C major", year: 1921, form: "concerto" },
      { title: "Symphony No. 1 'Classical'", year: 1917, form: "symphony" },
      { title: "Symphony No. 5", year: 1944, form: "symphony" },
      { title: "Alexander Nevsky", year: 1939, form: "cantata" },
    ],
    descriptionPrompts: [
      "Wrote 'Peter and the Wolf' (1936) to teach children the instruments of the orchestra.",
      "His Classical Symphony (1917) is a Modernist wink at Haydn — neoclassicism before the term existed.",
      "Returned to Stalin's USSR in 1936 — denounced for 'formalism' in 1948 — died the same day as Stalin in 1953.",
      "Sharp, percussive, sardonic — yet capable of the deepest Romantic lyricism (Romeo and Juliet, Cinderella).",
    ],
    audioSearchTerms: [
      "Prokofiev Romeo and Juliet Montagues and Capulets",
      "Prokofiev Peter and the Wolf",
      "Prokofiev Classical Symphony",
    ],
  },
  {
    id: "shostakovich",
    name: "Dmitri Shostakovich",
    period: "modernism",
    era: "20th-century",
    birthYear: 1906,
    deathYear: 1975,
    nationality: "Russian (Soviet)",
    bio: "Wrote 15 symphonies and 15 string quartets under Stalin and his successors — denounced twice by Pravda, survived by writing music with two faces: public bombast and private irony.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Symphony No. 5 in D minor", year: 1937, form: "symphony" },
      { title: "Symphony No. 7 'Leningrad'", year: 1941, form: "symphony" },
      { title: "Symphony No. 10 in E minor", year: 1953, form: "symphony" },
      { title: "String Quartet No. 8 in C minor", year: 1960, form: "string quartet" },
      { title: "Lady Macbeth of Mtsensk", year: 1934, form: "opera" },
      { title: "Cello Concerto No. 1", year: 1959, form: "concerto" },
    ],
    descriptionPrompts: [
      "Composed under Stalin's terror — denounced twice in Pravda, both times for being insufficiently 'Soviet.'",
      "His Fifth Symphony (1937) was billed as 'a Soviet artist's reply to just criticism' — a tightrope of public conformity and private irony.",
      "His Seventh ('Leningrad') Symphony was smuggled out of the besieged city in microfilm and played around the world in 1942.",
      "15 string quartets — many secretly autobiographical — are his deepest, least public statements.",
      "Signed his late works with the DSCH motif: D-Eb-C-B (his German-spelling initials).",
    ],
    audioSearchTerms: [
      "Shostakovich Waltz No 2 Jazz Suite",
      "Shostakovich Symphony No 5 finale",
      "Shostakovich String Quartet No 8",
    ],
  },

  // ============ Post-1945 ============
  {
    id: "messiaen",
    name: "Olivier Messiaen",
    period: "post-1945",
    era: "20th-century",
    birthYear: 1908,
    deathYear: 1992,
    nationality: "French",
    bio: "Devout Catholic, ornithologist, organist at La Trinité in Paris for sixty years, and teacher of Boulez, Stockhausen, and half the post-war avant-garde. Built a musical vocabulary on modes of limited transposition, birdsong, and divine contemplation.",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Quatuor pour la fin du temps", year: 1941, form: "chamber" },
      { title: "Turangalîla-Symphonie", year: 1948, form: "symphony" },
      { title: "Vingt regards sur l'enfant-Jésus", year: 1944, form: "piano cycle" },
      { title: "Catalogue d'oiseaux", year: 1958, form: "piano cycle" },
      { title: "Saint François d'Assise", year: 1983, form: "opera" },
    ],
    descriptionPrompts: [
      "Wrote the 'Quartet for the End of Time' (1941) in a German POW camp on whatever instruments his fellow prisoners had.",
      "Devout Catholic and ornithologist — transcribed birdsong as raw material for his music.",
      "Built his vocabulary on 'modes of limited transposition' — scales whose symmetry restricts how they can move.",
      "Taught at the Paris Conservatoire for decades — Boulez, Stockhausen, Xenakis, and half the post-war avant-garde studied with him.",
    ],
    audioSearchTerms: [
      "Messiaen Quatuor pour la fin du temps",
      "Messiaen Turangalila",
      "Messiaen Vingt regards",
    ],
  },
  {
    id: "cage",
    name: "John Cage",
    period: "post-1945",
    era: "20th-century",
    birthYear: 1912,
    deathYear: 1992,
    nationality: "American",
    bio: "Schoenberg's American student who, after a decade of percussion ensembles and prepared piano, embraced indeterminacy and chance — and redefined what could count as music with works like '4'33\"' (1952).",
    primaryForm: "keyboard",
    signatureWorks: [
      { title: "4'33\"", year: 1952, form: "any instrument" },
      { title: "Sonatas and Interludes for Prepared Piano", year: 1948, form: "prepared piano" },
      { title: "Music of Changes", year: 1951, form: "piano" },
      { title: "Imaginary Landscape No. 4", year: 1951, form: "12 radios" },
      { title: "In a Landscape", year: 1948, form: "piano / harp" },
    ],
    descriptionPrompts: [
      "Wrote a piece (4'33\") in which the performer plays nothing — the music is whatever ambient sound happens.",
      "Pioneered the 'prepared piano' — bolts, screws, and erasers wedged between piano strings.",
      "Embraced chance procedures (I Ching coin tosses) to compose, abolishing the composer's intentional control.",
      "Schoenberg's American student who eventually concluded that any sound could be music.",
    ],
    audioSearchTerms: [
      "Cage In a Landscape",
      "Cage Sonatas and Interludes Sonata V",
      "Cage prepared piano",
    ],
  },
  {
    id: "britten",
    name: "Benjamin Britten",
    period: "post-1945",
    era: "20th-century",
    birthYear: 1913,
    deathYear: 1976,
    nationality: "English",
    bio: "20th-century English opera's central figure — wrote 'Peter Grimes' (1945), the 'War Requiem' (1962), and church parables for his lifelong partner the tenor Peter Pears.",
    primaryForm: "opera",
    signatureWorks: [
      { title: "Peter Grimes", year: 1945, form: "opera" },
      { title: "War Requiem", year: 1962, form: "requiem" },
      { title: "The Young Person's Guide to the Orchestra", year: 1946, form: "orchestral" },
      { title: "Serenade for Tenor, Horn and Strings", year: 1943, form: "song cycle" },
      { title: "A Ceremony of Carols", year: 1942, form: "choral" },
      { title: "Billy Budd", year: 1951, form: "opera" },
    ],
    descriptionPrompts: [
      "20th-century English opera's central figure — 'Peter Grimes' (1945) revived English opera after a 250-year drought.",
      "Wrote 'The Young Person's Guide to the Orchestra' (1946) as a film score introducing children to each instrument.",
      "'War Requiem' (1962) sets Wilfred Owen's anti-war poetry against the Latin Requiem, premiered in the rebuilt Coventry Cathedral.",
      "Wrote his great works for his lifelong partner, the tenor Peter Pears.",
    ],
    audioSearchTerms: [
      "Britten Young Person's Guide to the Orchestra",
      "Britten Four Sea Interludes Peter Grimes",
      "Britten War Requiem Dies Irae",
    ],
  },
  {
    id: "ligeti",
    name: "György Ligeti",
    period: "post-1945",
    era: "20th-century",
    birthYear: 1923,
    deathYear: 2006,
    nationality: "Hungarian (later Austrian)",
    bio: "Hungarian-Jewish composer who survived a forced-labour camp, escaped to the West in 1956, and developed the dense 'micropolyphonic' style heard by millions through Kubrick's '2001: A Space Odyssey.'",
    primaryForm: "orchestral",
    signatureWorks: [
      { title: "Atmosphères", year: 1961, form: "orchestral" },
      { title: "Lux aeterna", year: 1966, form: "choral" },
      { title: "Requiem", year: 1965, form: "requiem" },
      { title: "Études for piano (Books 1-3)", year: 1985, form: "piano études" },
      { title: "Le Grand Macabre", year: 1977, form: "opera" },
    ],
    descriptionPrompts: [
      "Kubrick used four of his pieces in '2001: A Space Odyssey' — without telling him until afterward.",
      "Developed 'micropolyphony' — dense vocal/instrumental textures of dozens of independent lines bunched into clouds.",
      "Survived Holocaust forced labour as a Hungarian Jew; escaped to the West in 1956.",
      "Late piano études (1985–2001) are some of the most rhythmically intricate works ever written for the instrument.",
    ],
    audioSearchTerms: [
      "Ligeti Atmospheres",
      "Ligeti Lux Aeterna",
      "Ligeti Etudes for Piano",
    ],
  },

  // ============ Contemporary ============
  {
    id: "reich",
    name: "Steve Reich",
    period: "contemporary",
    era: "20th-century",
    birthYear: 1936,
    deathYear: null,
    nationality: "American",
    bio: "Co-founder of American minimalism — developed 'phasing' (two identical patterns slowly going out of sync) in 1965, and built a body of work on repetition, gradual process, and ensemble interlock.",
    primaryForm: "chamber",
    signatureWorks: [
      { title: "Music for 18 Musicians", year: 1976, form: "chamber" },
      { title: "Different Trains", year: 1988, form: "string quartet + tape" },
      { title: "Drumming", year: 1971, form: "percussion ensemble" },
      { title: "Tehillim", year: 1981, form: "voices and ensemble" },
      { title: "Come Out", year: 1966, form: "tape piece" },
      { title: "Clapping Music", year: 1972, form: "two performers" },
    ],
    descriptionPrompts: [
      "Co-invented minimalism in 1960s New York — developed the 'phasing' technique with looped tape.",
      "'Music for 18 Musicians' (1976) — an hour of slowly shifting pulses and interlocking ensemble patterns.",
      "'Different Trains' (1988) weaves recorded voices into a string quartet — Holocaust history through fragmented testimony.",
      "Steady pulse, audible repetition, gradual process — minimalism's American patriarch.",
    ],
    audioSearchTerms: [
      "Steve Reich Clapping Music",
      "Steve Reich Music for 18 Musicians",
      "Steve Reich Different Trains",
    ],
  },
  {
    id: "glass",
    name: "Philip Glass",
    period: "contemporary",
    era: "20th-century",
    birthYear: 1937,
    deathYear: null,
    nationality: "American",
    bio: "The most-performed American composer alive — drove a taxi in New York while writing 'Einstein on the Beach' (1976), now author of 25 operas, 14 symphonies, and dozens of film scores.",
    primaryForm: "opera",
    signatureWorks: [
      { title: "Einstein on the Beach", year: 1976, form: "opera" },
      { title: "Glassworks", year: 1981, form: "ensemble" },
      { title: "Akhnaten", year: 1983, form: "opera" },
      { title: "Symphony No. 3", year: 1995, form: "symphony" },
      { title: "Koyaanisqatsi (film score)", year: 1982, form: "film score" },
      { title: "Études for piano", year: 2012, form: "piano études" },
    ],
    descriptionPrompts: [
      "Drove a taxi in New York while composing 'Einstein on the Beach' (1976) — five-hour opera with no plot.",
      "Repeating arpeggios, additive process, slow harmonic change — his unmistakable signature.",
      "Wrote 25+ operas, 14 symphonies, and film scores from 'Koyaanisqatsi' to 'The Hours.'",
      "Studied with Nadia Boulanger and (informally) Ravi Shankar — Indian classical music shaped his rhythmic sense.",
    ],
    audioSearchTerms: [
      "Philip Glass Opening Glassworks",
      "Philip Glass Akhnaten",
      "Philip Glass Metamorphosis",
    ],
  },
  {
    id: "part",
    name: "Arvo Pärt",
    period: "contemporary",
    era: "20th-century",
    birthYear: 1935,
    deathYear: null,
    nationality: "Estonian",
    bio: "Soviet-Estonian composer who, after a serial period, fell silent for eight years and emerged with the 'tintinnabuli' style — simple triadic chords interleaved with a slow melodic line, rooted in chant.",
    primaryForm: "choral",
    signatureWorks: [
      { title: "Spiegel im Spiegel", year: 1978, form: "violin / piano" },
      { title: "Tabula rasa", year: 1977, form: "two violins, prepared piano, strings" },
      { title: "Fratres", year: 1977, form: "chamber" },
      { title: "Cantus in Memoriam Benjamin Britten", year: 1977, form: "string orchestra" },
      { title: "Berliner Messe", year: 1990, form: "mass" },
    ],
    descriptionPrompts: [
      "Soviet-Estonian composer who fell silent for eight years and emerged with a wholly new 'tintinnabuli' style.",
      "Tintinnabuli — 'little bells' — simple triadic chords interleaved with a slow stepwise melody.",
      "Devoutly Orthodox; his music is rooted in chant, silence, and a stripped-back medievalism.",
      "Among the most-performed living composers — Spiegel im Spiegel, Fratres, Tabula rasa have become modern standards.",
    ],
    audioSearchTerms: [
      "Arvo Pärt Spiegel im Spiegel",
      "Arvo Pärt Für Alina",
      "Arvo Pärt Cantus Britten",
    ],
  },
];

export function getComposerById(id: string): Composer | undefined {
  return COMPOSERS.find((c) => c.id === id);
}

export function getPeriodForComposer(composer: Composer): Period | undefined {
  return getPeriodById(composer.period);
}

export function getComposersByPeriod(periodId: string): Composer[] {
  return COMPOSERS.filter((c) => c.period === periodId);
}

// Re-export for convenience.
export { PERIODS, getPeriodById };
export type { Period };
